apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: consumer
  namespace: springboot-cloud
spec:
  host: consumer-v1.springboot-cloud.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1