apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: consumer-header-filter
  namespace: springboot-cloud
spec:
  workloadSelector:
    labels:
      app: consumer
      version: gray
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.lua
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            inlineCode: |
              function envoy_on_request(request_handle)
                request_handle:headers():add("grayid", "canary")
                request_handle:headers():add("grayid2", "canary22")
              end
              function envoy_on_response(response_handle)
                response_handle:headers():add("test", "from envoy filter response")
              end