apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-v2
  namespace: springboot-cloud
  labels:
    app: provider-v2
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider-v2
      version: v2
  template:
    metadata:
      labels:
        app: provider-v2
        version: v2
    spec:
      containers:
      - image: docker.io/song1206/provider:v2
        name: provider-v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8081


---
apiVersion: v1
kind: Service
metadata:
  name: provider-v2
  namespace: springboot-cloud
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: provider-v2