apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: spring-gateway
  namespace: springboot-cloud
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

# kubectl label ns springboot-cloud istio-injection=enabled
